### ISSUE TITLE
Export Doesn't Include Buffs and Debuffs

### ISSUE THREAD

**Issue by PiERiT** [marisa-ashkandi/tbcsim#111]
In the web version (tbcsim.com), Buffs and Debuffs are not selected when uploading a previously exported .yaml file. Even if you specify them beforehand by picking a preset, as soon as you upload the .yaml file, they are all wiped.

**Comment by secretbis** [comment]
Sorry, I wasn't able to reproduce this - buffs and debuffs were correctly reflected in all my exported presets.  

If you have a preset that fails, please attach it and reopen this!

**Comment by PiERiT** [comment]
One is attached. I had to change extension from yaml to txt to be able to upload it. 

[exported-preset.txt](https://github.com/marisa-ashkandi/tbcsim/files/7634418/exported-preset.txt)

All I'm doing is selecting Beast Mastery Hunter (phase 2) for preset, then clicking Export. If I then click Upload and select the file, it removes all of the buffs as they're not present anywhere in the file.
