### ISSUE TITLE
Shadow Priest - Hit from talents not working

### ISSUE THREAD

**Issue by Plankee** [marisa-ashkandi/tbcsim#113]
Hi,

I recently tried to sim some gearing options for my shadow priest and noticed that hit from talents are not working correctly. 
From what I can see in the GUI only hit from gear is being added to the totalt %.
After running a simulation the results also indicate that total hit is not calculated correctly, based on simulations I did 3 weeks+ ago.

Best regards 
Plankee

**Comment by secretbis** [comment]
Sorry about this!  There was a WIP refactor of spell mechanics that inadvertently got lumped in with another change.  It has been reverted.
