### ISSUE TITLE
Spriest DPS Loss From Changes?

### ISSUE THREAD

**Issue by CyberQuackGames** [marisa-ashkandi/tbcsim#114]
Noticing 400-500 dps loss on P2 Spriest (maybe other sets) from latest round of changes. Any work go into change how spells / procs or anything specific which would cause this?

Showing 900 dps range for P2, but should be around 1300-1400.

**Comment by Plankee** [comment]
I have noticed the same thing.
To me it looks like hit from talents are not being added to the totalt hit % (only hit from gear is added).

Seeing that hit cap is a big factor for Spriests it makes sense with the numbers we are getting atm.

**Comment by secretbis** [comment]
Sorry about this!  There was a WIP refactor of spell mechanics that inadvertently got lumped in with another change.  It has been reverted.
