### ISSUE TITLE
tbcsim some dps output looks wrong

### ISSUE THREAD

**Issue by veryloong** [marisa-ashkandi/tbcsim#115]
I was testing some phase 2 dps for enhancement shaman, when i noticed that switching from dual wield netherbane to dual wield merciless gladiator cleaver resulted in a huge dps drop, even though MGC has superior damage and stats. tested repeatedly. 

additionally, deathblow goggles for mail engineering isnt in the list.

**Comment by secretbis** [comment]
Hmm, I get similar results for both weapon sets - definitely within normal variance.  Did you perhaps forget to reapply Mongoose to one of the test cases?

Looks like Wowhead had Surestrike miscategorized - I'll update the phase data, and you can see it in the meantime by selecting the Phase 5 item filter.
