### ISSUE TITLE
Use tables instead of divs for results

### ISSUE THREAD

**Issue by ChadLevy** [marisa-ashkandi/tbcsim#116]
The results area is not exportable to spreadsheet applications such as Excel and Google Sheets due to the underlying HTML being divs instead of tables. Importing tabular data to such applications is problematic if the source is not a standard HTML table.

**Comment by secretbis** [comment]
Changing the rendered structure isn't simple, as the UI library doesn't allow replacing render structure.  However, I have added CSV/TSV export to each table instead.

Please let me know if any other tabular formatting options would be useful!

![image](https://user-images.githubusercontent.com/56484534/142721263-25cc39af-3eb5-48aa-b4d2-330a48eeca18.png)

![image](https://user-images.githubusercontent.com/56484534/142721268-8f26b03b-1e90-4def-8433-26274639421c.png)
