### ISSUE TITLE
Export Doesn't Include Buffs and Debuffs

### ISSUE THREAD

**Issue by PiERiT** [marisa-ashkandi/tbcsim#123]
I can't seem to reopen #111 so I made a new issue.

In the web version (tbcsim.com), Buffs and Debuffs are not selected when uploading a previously exported .yaml file. Even if you specify them beforehand by picking a preset, as soon as you upload the .yaml file, they are all wiped.

An export is attached. I had to change the extension from yaml to txt to be able to upload it. All I'm doing is selecting Beast Mastery Hunter (phase 2) for preset, then clicking Export. If I then click Upload and select the file, it removes all of the buffs as they're not present anywhere in the file.

[exported-preset.txt](https://github.com/marisa-ashkandi/tbcsim/files/7656334/exported-preset.txt)

**Comment by secretbis** [comment]
Apologies for misunderstanding your issue the first time - I've found the issue, and it should now be fixed.  Re-exporting should fix the preset, even if you've uploaded a current preset export.
