### ISSUE TITLE
Missing Items

### ISSUE THREAD

**Issue by PiERiT** [marisa-ashkandi/tbcsim#124]
JC-only gems (like Crimson Sun), as well as most Band of Eternity rings, appear to be missing from tbcsim.com. Is it easy enough to add those?

**Comment by secretbis** [comment]
All Band of Eternity variants are present, but you may need to update the item filter to Phase 3 to see anything beyond the base model.

Adding JC-only gems should be no problem!

**Comment by PiERiT** [comment]
Thanks. For some reason the only ring visible to me with a Phase 2 filter is Band of Eternity (Restorer, Honored). The rest are only visible in Phase 3. But I can just switch to that, no problem.
