### ISSUE TITLE
Enhancement Annihilator OH Set doesn't have Annihilator OH

### ISSUE THREAD

**Issue by Ryukerg** [marisa-ashkandi/tbcsim#21]
![image](https://user-images.githubusercontent.com/18726280/112708632-69b40000-8e89-11eb-90d1-34a34b940bbf.png)

Selecting the Annihilator OH Set for Enhancement Shamans gives a set with 2x Dragonmaw instead of 1x Dragonmaw, 1x Annihilator OH.

**Comment by secretbis** [comment]
Thanks for the report!
