### ISSUE TITLE
missing buffs / debuffs

### ISSUE THREAD

**Issue by mchypnotoad** [marisa-ashkandi/tbcsim#26]
missing buffs:
bloodlust
ferocious inspiration (as of right now, the buff can be selected only once, in reality it stacks for every BM hunter in group, so it should be 0-5 times selectable)

missing debuffs: 
improved faerie fire

**Comment by secretbis** [comment]
Thanks for the feedback!  I had been holding off on Lust for a minute, until the possibility of rotating shamans through groups was confirmed or denied.  No word from Blizz, so I suppose I should at least do single Lust.

Regarding FI, it's a flat all-damage modifier - you can safely just multiply the final result by 1.03 X additional times.  Be careful not to assume any impossible groups, though.

**Comment by secretbis** [comment]
FI/FF are now implemented.  Will track Lust addition in #34
