### ISSUE TITLE
Scope issues

### ISSUE THREAD

**Issue by Zeramus** [marisa-ashkandi/tbcsim#29]
1. Khorium Scope is missing
2. Stabilized Eternium Scope provides 0 Crit rating as per the tooltip and does not work on the total crit rating either. 
![Scope](https://user-images.githubusercontent.com/82423416/114480102-d6d8cc80-9bcf-11eb-9f1d-a20ec424291e.JPG)

**Comment by secretbis** [comment]
Added Khorium Scope, and fixed the UI display for "special" crit values (e.g. bow/gun).  Not much I can do about the tooltips, I'm afraid - gotta wait for Wowhead to be un-scuffed.
