### ISSUE TITLE
Hunter shot cast times incorrect

### ISSUE THREAD

**Issue by fusionpit** [marisa-ashkandi/tbcsim#43]
Non-instant ranged attacks have a built in 0.5 second delay, which affects the cast time of Mult-Shot, Aimed Shot, and Steady Shot. [See here.](https://www.mmo-champion.com/content/2188-Patch-4-0-6-Feb-22-Hotfixes-Blue-Posts-Artworks-Comic) This additional time is added to the base cast time of these spells before haste is taken into account.

Additionally, Auto Shot has a 0.5 second cast time, which is reduced by haste. Auto Shot will begin casting at `(weaponSpeed-0.5)/totalHaste` seconds after the last cast of Auto Shot, and cast for `0.5/totalHaste` seconds.

**Comment by secretbis** [comment]
Wow, that's quite odd - thanks for pointing that out!  Strangely enough, after accounting for haste on Steady (which was also missing), it comes out somewhat even.
