### ISSUE TITLE
Arms Warrior Incorrectly Getting Rampage

### ISSUE THREAD

**Issue by TheGroxEmpire** [marisa-ashkandi/tbcsim#5]
If you simmed Fury Warrior preset and then switching to Arms after, Arms preset would get rampage buffs without the preset having the talent for it:
<details>

![image](https://user-images.githubusercontent.com/47816228/110773415-4d13a780-828f-11eb-8b7c-eb3ee25ff5e2.png)
</details>

**Comment by secretbis** [comment]
Thanks for the report!  This was stale UI state, and is now fixed.
