### ISSUE TITLE
Trinket Sim Problems

### ISSUE THREAD

**Issue by Simplejakk** [marisa-ashkandi/tbcsim#57]
When simming, Berserker's Call, Shard of Contempt, Madness of the Betrayer, Blackened Naaru Sliver and Warp-Spring Coil appear to not sim properly.

-Simplejakk

**Comment by secretbis** [comment]
@Simplejakk Thanks for the report!  Which class were you simming at the time - Rogue, I presume?

**Comment by Simplejakk** [comment]
I believe I found those problems while simming for a bm hunter. I’m organizing a table of trinkets for my guild – it looks like it affects multiple classes/specs. For example:
things like Blackened Naaru Sliver seem lower than expected for Enhancement Shaman. Berserker’s Call is a stronger version of Bloodlust Brooch but it’s lower almost across
the board. I’ll attach my table of trinket values. They assume close to full BiS Sunwell gear, 1000 iterations, 30sec variance.

-Simplejakk





Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Simplejakk** [comment]
[TBC Trinket List.ods](https://github.com/marisa-ashkandi/tbcsim/files/6497190/TBC.Trinket.List.ods)
 
Sorry, here is my trinket list.

**Comment by Simplejakk** [comment]
I don't know if it helps but I've noticed that the trinkets that don't sim properly are the trinkets that aren't found in 'Phase 1' of TBC.
