### ISSUE TITLE
Hunter Weightstone does not increase dps in sim

### ISSUE THREAD

**Issue by silyar** [marisa-ashkandi/tbcsim#75]
Using Fistweapons with either "Bugged Hunter Stone" or "Weightstone" does not increase the sims dps.
Tested with BM P1-BiS + Claw of the Watcher + Stormreaver Warblades both with 15 Agi Enchant.

**Comment by secretbis** [comment]
I've checked this, and the Bugged Hunter Weightstone is correctly affecting ranged attacks.  Thanks for the report, though!
