### ISSUE TITLE
Implement weapon enhancements

### ISSUE THREAD

**Issue by batboywonder** [marisa-ashkandi/tbcsim#82]
Hi,
I was playing around with enhancement shaman and noticed that the sim assumes both weapons have windfury. Is there a way you could implement choosing which enhancement is on which weapon? I would want to see if flametongue is a better choice when I have a fast off-hand.
Thanks, great work so far!

**Comment by secretbis** [comment]
These are actually part of the rotation, which you can edit on the right side of the page.  Just change `Windfury Weapon (OH)` to `Flametongue Weapon (OH)` and you should be good to go!
