### ISSUE TITLE
Spec changes

### ISSUE THREAD

**Issue by Bonzii70** [marisa-ashkandi/tbcsim#84]
Hello your simulator seems to function quite well. Is there any way to change specific talents?
For example I would like to compare hunter DPS in survival spec while using improved aspect of the Hawk instead of mortal shots. I tried changing what was written in the talents dropdown but it did not seem to have good effects.

**Comment by secretbis** [comment]
You can change them in the UI, but be sure that it is valid JSON, and the ability name is exactly correct (including case).  You can lookup the ability in the source code to find the name the simulator expects.

The simplest way would be to download a preset file, modify the talents there, then reimport.  Easiest for human editing.
