### ISSUE TITLE
Stabilized Eternium Scope not working

### ISSUE THREAD

**Issue by PrinzValium80** [marisa-ashkandi/tbcsim#89]
Hi,

Stabilized Eternium Scope seems to do nothing, should increase +28 crit rating.
Could you please fix it.
The bugs makes hunter calculation pointless at the moment.

Best regards;

**Comment by secretbis** [comment]
Thanks for the report - looks like it wasn't correctly applying to crossbows, specifically.  All other weapon types are working as expected.
