### ISSUE TITLE
Protection Warrior Support

### ISSUE THREAD

**Issue by Smokywood-Myzreal** [marisa-ashkandi/tbcsim#94]
Any chance it would be possible to add support for protection warriors for those times we aren't tanking and want to optimize what little DPS we do?

**Comment by secretbis** [comment]
I think that's pretty achievable - only needs a Devastate implementation, a couple talents, and a preset or two.  I assume Prot DPS BIS would basically mirror Fury BIS?

**Comment by Smokywood-Myzreal** [comment]
I think stat weights are going to be different.

Bloodthirst scales on AP, Devastate scales on weapon damage only. Crit is also going to be devalued due to lacking Rampage.
